# Generated by Django 4.1.2 on 2022-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatru', '0002_employee_delete_angajat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='placeholder', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee_pics'),
        ),
    ]
