# Generated by Django 4.1.2 on 2022-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatru', '0005_actor_announcement_play_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(default='placeholder', max_length=30),
        ),
    ]
