# Generated by Django 4.1.2 on 2022-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatru', '0006_announcement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.TextField(),
        ),
    ]
