# Generated by Django 4.1.2 on 2022-10-22 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatru', '0007_alter_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 15, 3, 30, 507074)),
        ),
    ]
